LIOLogicalUnit: Medium: add promote operation

diff --git a/heartbeat/LIOLogicalUnit b/heartbeat/LIOLogicalUnit
--- a/heartbeat/LIOLogicalUnit
+++ b/heartbeat/LIOLogicalUnit
@@ -510,6 +510,37 @@ LIOLogicalUnit_monitor() {
     return $OCF_NOT_RUNNING
 }
 
+LIOLogicalUnit_promote() {
+	# Keep trying to promote the resource;
+	# wait for the CRM to time us out if this fails
+	while true; do
+		LIOLogicalUnit_monitor
+                rc=$?
+
+		case $rc in
+		$OCF_SUCCESS)
+                    ocf_run tcm_node --setaluastate iblock_${OCF_RESKEY_lio_iblock}/${OCF_RESOURCE_INSTANCE} $(crm_node -n) o || {
+                        ocf_log error "Unable to set ALUA access state for lun_${OCF_RESKEY_lun}/${OCF_RESOURCE_INSTANCE} to active/optimized!";
+                        exit $OCF_ERR_GENERIC
+                    }
+                    ocf_log debug "ALUA: promote successfull, TPG $(crm_node -n) is now optimized"
+		    ;;
+		$OCF_NOT_RUNNING)
+	            ocf_log error "Trying to promote resource ${OCF_RESOURCE_INSTANCE} that was not started"
+	            break
+	            ;;
+		$OCF_RUNNING_MASTER)
+	            ocf_log debug "Promotion successful"
+	            rc=$OCF_SUCCESS
+	            break
+	            ;;
+		esac
+		sleep 3
+	done
+
+	return $rc
+}
+
 LIOLogicalUnit_demote() {
 	# Keep trying to demote the resource;
 	# wait for the CRM to time us out if this fails
