SCSTTarget: initial rewrite of start operation from LIO to SCST

diff --git a/heartbeat/SCSTTarget b/heartbeat/SCSTTarget
--- a/heartbeat/SCSTTarget
+++ b/heartbeat/SCSTTarget
@@ -29,13 +29,13 @@
 OCF_RESKEY_fabric_default="iscsi"
 : ${OCF_RESKEY_fabric=${OCF_RESKEY_fabric_default}}
 
-# Listen on 0.0.0.0:3260 by default
-OCF_RESKEY_iscsi_portals_default="0.0.0.0:3260"
+# Listen on 0.0.0.0 by default
+OCF_RESKEY_iscsi_portals_default="0.0.0.0"
 : ${OCF_RESKEY_portals=${OCF_RESKEY_iscsi_portals_default}}
 
-# Lockfile, used for selecting a target ID
-LOCKFILE=${HA_RSCTMP}/SCSTTarget-${OCF_RESKEY_fabric}.lock
-
+# For convenience
+SCST_BASE="/sys/kernel/scst_tgt"
+FABRIC_BASE="${SCST_BASE}/targets/${OCF_RESKEY_fabric}"
 #######################################################################
 
 meta_data() {
@@ -84,18 +84,6 @@ ${OCF_RESKEY_iscsi_portals_default}.
 <content type="string" default="${OCF_RESKEY_iscsi_portals_default}"/>
 </parameter>
 
-<parameter name="allowed_initiators" required="0" unique="0">
-<longdesc lang="en">
-Allowed initiators. A space-separated list of initiators allowed to
-connect to this target. Initiators may be listed in any syntax
-the target implementation allows. If this parameter is empty or
-not set, access to this target will not be allowed from any initiator.
-</longdesc>
-<shortdesc lang="en">List of initiators allowed to connect
-to this target</shortdesc>
-<content type="string" default=""/>
-</parameter>
-
 <parameter name="additional_parameters" required="0" unique="0">
 <longdesc lang="en">
 Additional target parameters. A space-separated list of "name=value"
@@ -142,9 +130,9 @@ SCSTTarget_start() {
     local value
     local initiator
     local portal
-    local ports
-    local configfs_path
+    local sysfs_path
     local mod
+    local mods
     local ids
 
     # Be sure some default dirs are available
@@ -161,58 +149,64 @@ SCSTTarget_start() {
         }
     fi
 
-    # Load core modules and configfs if needed
-    if ! mountpoint -q /sys/kernel/config ; then
-	ocf_run -q modprobe -s configfs || {
-           ocf_log err "Unable to load configfs module";
-           return $OCF_ERR_INSTALLED
-        }
-        ocf_log debug "${OCF_RESOURCE_INSTANCE}: configfs module loaded"
-	ocf_run -q mount -t configfs configfs /sys/kernel/config || {
-           ocf_log err "Unable to mount configfs on /sys/kernel/config";
-           return $OCF_ERR_INSTALLED
-        }
-        ocf_log debug "${OCF_RESOURCE_INSTANCE}: configfs mounted on /sys/kernel/config"
-    fi
-    if [ ! -d /sys/kernel/config/target ]; then
-        for mod in mod iblock pscsi file ; do
-           ocf_run -q modprobe -s  target_core_${mod} || {
-              ocf_log err "Unable to load target_core_${mod} module";
+    # Load core modules if needed
+    if [ ! -d /sys/kernel/scst_tgt ]; then
+        for mod in scst scst_vdisk scst_disk; do
+           ocf_run -q modprobe -s $mod || {
+              ocf_log err "Unable to load ${mod} module";
               return $OCF_ERR_INSTALLED
            }
-           ocf_log debug "${OCF_RESOURCE_INSTANCE}: target_core_${mod} module loaded."
+           ocf_log debug "${OCF_RESOURCE_INSTANCE}: ${mod} module loaded."
         done
     fi
 
-    # lio distinguishes between targets and target portal
-    # groups (TPGs). We will always create one TPG, with the
-    # number 1. In lio, creating a network portal
-    # automatically creates the corresponding target if it
-    # doesn't already exist.
+    # Intel Nehalem processor supports hardware accelerated crc32
+    # algorithm with the new CRC32 instruction in SSE 4.2 instruction set.
+    if grep -q ' sse4_2 ' /proc/cpuinfo; then
+        other_mods="crc32c-intel"
+    else
+        other_mods="crc32"
+    fi
+
+    # Load extra modules
+    for mod in $other_mods; do
+      ocf_run -q modprobe -s  target_core_${mod} || {
+         ocf_log err "Unable to load ${mod} module";
+         return $OCF_ERR_INSTALLED
+      }
+      ocf_log debug "${OCF_RESOURCE_INSTANCE}: ${mod} module loaded."
+    done
+
+    # Create the target and portals
     case ${OCF_RESKEY_fabric} in
         iscsi)
             # Initiate the fabric if needed
-            if [ ! -d /sys/kernel/config/target/${OCF_RESKEY_fabric} ]; then
-                ocf_run -q modprobe -s  iscsi_target_mod || {
-                   ocf_log err "Unable to load iscsi_target_mod  module";
+            if [ ! -d ${FABRIC_BASE} ]; then
+                ocf_run -q modprobe -s  iscsi_scst || {
+                   ocf_log err "Unable to load iscsi_scst  module";
                    return $OCF_ERR_INSTALLED
                 }
-                ocf_log debug "${OCF_RESOURCE_INSTANCE}: iscsi_target_mod module loaded."
-                ocf_run -q mkdir -p /sys/kernel/config/target/iscsi || {
-                   ocf_log err "Unable to create iscsi target configfs entry";
-                   return $OCF_ERR_INSTALLED
-                }
-                ocf_log debug "${OCF_RESOURCE_INSTANCE}: iscsi configfs entry created"
-                ocf_run -q echo -n 0 > /sys/kernel/config/target/iscsi/discovery_auth/enforce_discovery_auth || {
-                   ocf_log err "Unable to disable enforce of iSCSI Discovery authentication";
-                   return $OCF_ERR_INSTALLED
-                }
+                ocf_log debug "${OCF_RESOURCE_INSTANCE}: iscsi_scst module loaded."
             fi
-            ports=${OCF_RESKEY_iscsi_portals}
-            for portal in ${ports}; do
-              ocf_run -q lio_node --addnp ${OCF_RESKEY_id} 1 \
-                  ${portal} || exit $OCF_ERR_GENERIC
-            done
+
+            # Create the target
+            ocf_run -q echo "add_target ${OCF_RESKEY_id}" >${FABRIC_BASE}/mgmt || {
+                ocf_log err "Unable to create target ${OCF_RESKEY_id}.";
+                exit $OCF_ERR_GENERIC
+            }
+            ocf_log debug "${OCF_RESOURCE_INSTANCE}: iSCSI target ${OCF_RESKEY_id} initialized"
+
+            # Define allowed portals
+            if [ "${OCF_RESKEY_iscsi_portals}" != "${OCF_RESKEY_iscsi_portals_default}" ]; then
+                for portal in ${OCF_RESKEY_iscsi_portals}; do
+                    ocf_run -q echo "add_target_attribute ${OCF_RESKEY_id} allowed_portal ${portal}" >${FABRIC_BASE}/mgmt || {
+                        ocf_log err "Unable to set allowed portal ${portal} on target ${OCF_RESKEY_id}.";
+                        exit $OCF_ERR_GENERIC
+                    }
+                done
+                ocf_log debug "${OCF_RESOURCE_INSTANCE}: Allowed portals on target ${OCF_RESKEY_id} are set to: ${OCF_RESKEY_iscsi_portals}."
+            fi
+
         ;;
         qla2xxx)
             # Initiate the fabric if needed
@@ -241,44 +235,50 @@ SCSTTarget_start() {
         ;;
     esac
 
-    # in lio, we can set target parameters by manipulating
-    # the appropriate configfs entries
+    # Set specific target parameters for the target
     for param in ${OCF_RESKEY_additional_parameters}; do
 	name=${param%=*}
 	value=${param#*=}
         for ids in ${OCF_RESKEY_id}; do
-	    configfs_path="/sys/kernel/config/target/${OCF_RESKEY_fabric}/${ids}/tpgt_1/param/${name}"
+	    sysfs_path="${FABRIC_BASE}/${ids}/${name}"
 	    if [ -e ${configfs_path} ]; then
-	        echo ${value} > ${configfs_path} || exit $OCF_ERR_GENERIC
+	        echo "${value}" >${configfs_path} || exit $OCF_ERR_GENERIC
 	    else
 	        ocf_log warn "Unsupported ${OCF_RESKEY_fabric} target parameter ${name}: will be ignored."
 	    fi
         done
     done
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set specific parameter ${OCF_RESKEY_additional_parameters} for target ${OCF_RESKEY_id}"
 
-    # lio does per-initiator filtering by default.
-    # NO DEMO MODE enabled
-    if [ -n "${OCF_RESKEY_allowed_initiators}" ]; then
-        for ids in ${OCF_RESKEY_id}; do
-	    for initiator in ${OCF_RESKEY_allowed_initiators}; do
-                ocf_run -q lio_node --addnodeacl ${ids} 1 \
-                ${initiator} || exit $OCF_ERR_GENERIC
-	    done
-        done
-    fi
-    # TODO: add CHAP authentication support when it gets added
-    # back into SCSTs iscsi target
-    if [ "${OCF_RESKEY_fabric}" = "iscsi" ]; then
-        ocf_run -q  lio_node --disableauth ${OCF_RESKEY_id} 1 || exit $OCF_ERR_GENERIC
-    fi 
-
-    # Finally, we need to enable the target to allow
-    # initiators to connect
+    # SCST targets must have a LUN 0 - create it on target creation.
+    # As the LUN access restrictions are handled at LUN level,
+    # put LUN 0 in the targets default group.
+    ocf_run -q echo "add_device nullio" >${SCST_BASE}/handlers/vdisk_nullio/mgmt || {
+        ocf_log err "Unable to create device for LUN 0 on target ${OCF_RESKEY_id}.";
+        exit $OCF_ERR_GENERIC
+    }
     for ids in ${OCF_RESKEY_id}; do
-        grep -q "1" /sys/kernel/config/target/${OCF_RESKEY_fabric}/${ids}/tpgt_1/enable \
-            || echo 1 > /sys/kernel/config/target/${OCF_RESKEY_fabric}/${ids}/tpgt_1/enable \
-            || exit $OCF_ERR_GENERIC
+        ocf_run -q echo "add nullio 0" >${FABRIC_BASE}/${ids}/luns/mgmt || {
+            ocf_log err "Unable to add LUN 0 to target ${OCF_RESKEY_id}.";
+            exit $OCF_ERR_GENERIC
+        }
     done
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Added dummy LUN 0 to target ${OCF_RESKEY_id}"
+
+    # Enable this specific target
+    for ids in ${OCF_RESKEY_id}; do
+        ocf_run -q echo "1" >"${FABRIC_BASE}/${ids}/enabled" || {
+            ocf_log err "Unable to enable target ${OCF_RESKEY_id}.";
+            exit $OCF_ERR_GENERIC
+        }
+        ocf_log debug "${OCF_RESOURCE_INSTANCE}: Enabled iSCSI target ${OCF_RESKEY_id}"
+    done
+
+    # Be sure all Targets are finally enabled
+    ocf_run -q echo "1" >"${FABRIC_BASE}/enabled" || {
+        ocf_log err "Unable to globaly enable ${OCF_RESKEY_fabric} targets.";
+        exit $OCF_ERR_GENERIC
+    }
 
     return $OCF_SUCCESS
 }
