SCSTLogicalUnit: truncate SCSI itentifiers to their maximum length
                 scsi_sn            to 8 bytes
                 vendor_id          to 8 bytes
                 product_id         to 16 bytes
                 scsi_id            to 24 bytes
                 vendor_specific_id to 24 bytes

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -44,8 +44,8 @@ OCF_RESKEY_allowed_initiators_default=""
 # and persistent in the event of resource migration.
 # SCSI IDs are limited to 24 bytes. To have a reasonably unique
 # default SCSI SN, use the first 24 bytes of an MD5 hash of
-# OCF_RESKEY_target_id and $OCF_RESOURCE_INSTANCE
-sn=`echo -n "${OCF_RESKEY_target_id} ${OCF_RESOURCE_INSTANCE}" | openssl md5 | sed -e 's/(stdin)= //'`
+# $OCF_RESOURCE_INSTANCE
+sn=`echo -n "${OCF_RESOURCE_INSTANCE}" | openssl md5 | sed -e 's/(stdin)= //'`
 OCF_RESKEY_scsi_id_default="${sn:0:24}"
 : ${OCF_RESKEY_scsi_id=${OCF_RESKEY_scsi_id_default}}
 : ${OCF_RESKEY_vendor_specific_id=${OCF_RESKEY_scsi_id}}
@@ -148,7 +148,7 @@ vdisk_fileio, vdisk_blockio, vcdrom, vdisk_nullio
 <parameter name="scsi_id" required="0" unique="1">
 <longdesc lang="en">
 The SCSI ID to be configured for this Logical Unit. The default
-is a hash of the target id and the resource name, truncated to 24 bytes.
+is a hash of the resource name, truncated to 24 bytes.
 </longdesc>
 <shortdesc lang="en">SCSI ID</shortdesc>
 <content type="string" default="${OCF_RESKEY_scsi_id_default}"/>
@@ -157,8 +157,8 @@ is a hash of the target id and the resource name, truncated to 24 bytes.
 <parameter name="scsi_sn" required="0" unique="1">
 <longdesc lang="en">
 The SCSI serial number to be configured for this Logical Unit.
-The default is a hash of the target id and the resource name,
-truncated to 8 bytes.
+The default is a hash of the resource name, truncated
+to 8 bytes.
 </longdesc>
 <shortdesc lang="en">SCSI serial number</shortdesc>
 <content type="string" default="${OCF_RESKEY_scsi_sn_default}"/>
@@ -166,7 +166,8 @@ truncated to 8 bytes.
 
 <parameter name="product_id" required="0" unique="1">
 <longdesc lang="en">
-The SCSI product ID to be configured for this Logical Unit.
+The SCSI product ID to be configured for this Logical Unit,
+truncated to 16 bytes.
 </longdesc>
 <shortdesc lang="en">SCSI product ID</shortdesc>
 <content type="string" />
@@ -174,7 +175,8 @@ The SCSI product ID to be configured for this Logical Unit.
 
 <parameter name="vendor_id" required="0" unique="1">
 <longdesc lang="en">
-The SCSI vendor ID to be configured for this Logical Unit.
+The SCSI vendor ID to be configured for this Logical Unit,
+truncated to 8 bytes.
 </longdesc>
 <shortdesc lang="en">SCSI vendor ID</shortdesc>
 <content type="string" default="${OCF_RESKEY_vendor_id_default}"/>
@@ -183,7 +185,8 @@ The SCSI vendor ID to be configured for this Logical Unit.
 <parameter name="vendor_specific_id" required="0" unique="1">
 <longdesc lang="en">
 The SCSI vendor specific ID to be configured for this Logical Unit.
-It defaults to the same value as the SCSI serial id.
+It defaults to the same value as the SCSI serial id, and is
+truncated to 24 bytes.
 </longdesc>
 <shortdesc lang="en">SCSI vendor specific ID</shortdesc>
 <content type="string" default="${OCF_RESKEY_scsi_id_default}"/>
@@ -550,26 +553,26 @@ SCSTLogicalUnit_start() {
 
     # Set the SCSI device id aka T10 device id
     if [ -n "${OCF_RESKEY_scsi_id}" ]; then
-        scst_sysfs_write "${OCF_RESKEY_scsi_id}" ${dev_path}/t10_dev_id || {
-            ocf_log err "Unable to set T10 device id ${OCF_RESKEY_scsi_id} for device ${OCF_RESOURCE_INSTANCE}.";
+        scst_sysfs_write "${OCF_RESKEY_scsi_id:0:24}" ${dev_path}/t10_dev_id || {
+            ocf_log err "Unable to set T10 device id ${OCF_RESKEY_scsi_id:0:24} for device ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
         }
     fi
-    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set SCSI device id to ${OCF_RESKEY_scsi_id}."
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set SCSI device id to ${OCF_RESKEY_scsi_id:0:24}."
 
     # Set the SCSI vendor specific id
     if [ -n "${OCF_RESKEY_vendor_specific_id}" ]; then
-        scst_sysfs_write "${OCF_RESKEY_vendor_specific_id}" ${dev_path}/vend_specific_id || {
-            ocf_log err "Unable to set vendor specific id ${OCF_RESKEY_vendor_specific_id} for device ${OCF_RESOURCE_INSTANCE}.";
+        scst_sysfs_write "${OCF_RESKEY_vendor_specific_id:0:24}" ${dev_path}/vend_specific_id || {
+            ocf_log err "Unable to set vendor specific id ${OCF_RESKEY_vendor_specific_id:0:24} for device ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
         }
     fi
-    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set SCSI vendor specific id to ${OCF_RESKEY_vendor_specific_id}."
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set SCSI vendor specific id to ${OCF_RESKEY_vendor_specific_id:0:24}."
 
     # Set the SCSI device serial number aka unit serial number
     if [ -n "${OCF_RESKEY_scsi_sn}" ]; then
-        scst_sysfs_write "${OCF_RESKEY_scsi_sn}" ${dev_path}/usn || {
-            ocf_log err "Unable to set usn ${OCF_RESKEY_scsi_sn} for device ${OCF_RESOURCE_INSTANCE}.";
+        scst_sysfs_write "${OCF_RESKEY_scsi_sn:0:8}" ${dev_path}/usn || {
+            ocf_log err "Unable to set usn ${OCF_RESKEY_scsi_sn:0:8} for device ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
         }
     fi
@@ -577,21 +580,21 @@ SCSTLogicalUnit_start() {
 
     # Set the SCSI product id
     if [ -n "${OCF_RESKEY_product_id}" ]; then
-        scst_sysfs_write "${OCF_RESKEY_product_id}" ${dev_path}/prod_id || {
-            ocf_log err "Unable to set product id ${OCF_RESKEY_product_id} for device ${OCF_RESOURCE_INSTANCE}.";
+        scst_sysfs_write "${OCF_RESKEY_product_id:0:15}" ${dev_path}/prod_id || {
+            ocf_log err "Unable to set product id ${OCF_RESKEY_product_id:0:15} for device ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
         }
     fi
-    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set vendor id to ${OCF_RESKEY_vendor_id}."
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set product id to ${OCF_RESKEY_product_id:0:15}."
 
     # Set the SCSI vendor id
     if [ -n "${OCF_RESKEY_vendor_id}" ]; then
-        scst_sysfs_write "${OCF_RESKEY_vendor_id}" ${dev_path}/t10_vend_id || {
-            ocf_log err "Unable to set usn ${OCF_RESKEY_vendor_id} for device ${OCF_RESOURCE_INSTANCE}.";
+        scst_sysfs_write "${OCF_RESKEY_vendor_id:0:8}" ${dev_path}/t10_vend_id || {
+            ocf_log err "Unable to set usn ${OCF_RESKEY_vendor_id:0:8} for device ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
         }
     fi
-    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set vendor id to ${OCF_RESKEY_vendor_id}."
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set vendor id to ${OCF_RESKEY_vendor_id:0:8}."
 
     # Prepare for ALUA if configured
     if [ -n "${OCF_RESKEY_alua_tpg}" ]; then
