SCSTLogicalUnit: block device before ALUA state change, unblock after

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -399,10 +399,15 @@ update_alua_access_state() {
             ;;
     esac
 
-    scst_sysfs_write "${2}" ${dev_group}/target_groups/${tpg}/state || {
-        ocf_log err "ALUA - Unable to set state to ${2} - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
-        exit $OCF_ERR_GENERIC
-    }
+    # If desired state is already set, don't block/unblock the device
+    if [ "$(scst_sysfs_read ${dev_group}/target_groups/${tpg}/state)" != ${2} ]; then
+        block_dev
+        scst_sysfs_write "${2}" ${dev_group}/target_groups/${tpg}/state || {
+            ocf_log err "ALUA - Unable to set state to ${2} - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
+            exit $OCF_ERR_GENERIC
+        }
+        unblock_dev
+    fi
     ocf_log debug "${OCF_RESOURCE_INSTANCE}: ALUA - TPG ${tpg} is in ${2} state."
 
     return $OCF_SUCCESS
