SCSTLogicalUnit: introduce unblock_dev and block_dev functions

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -345,6 +345,41 @@ flushbufs() {
     fi
 }
 
+block_dev() {
+    local block="${SCST_BASE}/devices/${OCF_RESOURCE_INSTANCE}/block"
+
+    # Block new commands for the device, drain current commands.
+    if [ -e "${block}" ]; then
+        ocf_log info "${OCF_RESOURCE_INSTANCE}: Waiting for device ${OCF_RESOURCE_INSTANCE} being blocked..."
+        # Check if device is already blocked
+        if [ "$(scst_sysfs_read ${block})" != "1 0" -a  "$(scst_sysfs_read ${block})" != "1 1" ]; then
+            # This is synchronous and waits for all running commands
+            # being drained.
+            scst_sysfs_write "1" ${block} || {
+                ocf_log err "Unable to block device ${OCF_RESOURCE_INSTANCE}.";
+                exit $OCF_ERR_GENERIC
+            }
+        fi
+        ocf_log info "${OCF_RESOURCE_INSTANCE}: Successfully blocked device ${OCF_RESOURCE_INSTANCE}."
+    fi
+}
+
+unblock_dev() {
+    local block="${SCST_BASE}/devices/${OCF_RESOURCE_INSTANCE}/block"
+
+    # Unblock the previously blocked device.
+    if [ -e "${block}" ]; then
+        # Check if device is already unblocked
+        if [ "$(scst_sysfs_read ${block})" != "0 0" -a  "$(scst_sysfs_read ${block})" != "0 1" ]; then
+            scst_sysfs_write "0" ${block} || {
+                ocf_log err "Unable to unblock device ${OCF_RESOURCE_INSTANCE}.";
+                exit $OCF_ERR_GENERIC
+            }
+        fi
+        ocf_log info "${OCF_RESOURCE_INSTANCE}: Successfully unblocked device ${OCF_RESOURCE_INSTANCE}."
+    fi
+}
+
 update_alua_access_state() {
     local tpg="$1"
     local dev_group="${SCST_BASE}/device_groups/${OCF_RESOURCE_INSTANCE}"
