SCSTLogicalUnit: Do ALUA state exactly as recommended
From scst/README:

1. Block all involved SCST devices using "block" sysfs attribute,
   wait until the blocking finished.
2. Change the ALUA state to "transitioning".
3. Perform the DRBD or other replication/failover SW state transition
4. Change the ALUA state to your desired secondary state.
5. Unblock the blocked on step 1 devices.

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -103,8 +103,8 @@ meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="SCSTLogicalUnit" version="0.4.2">
-<version>0.4.2</version>
+<resource-agent name="SCSTLogicalUnit" version="0.4.3">
+<version>0.4.3</version>
 
 <longdesc lang="en">
 Manages a Logical Unit for a SCST target. A Logical unit is a subdivision of
@@ -402,7 +402,15 @@ update_alua_access_state() {
     # If desired state is already set, don't block/unblock the device
     if [ "$(scst_sysfs_read ${dev_group}/target_groups/${tpg}/state)" != ${2} ]; then
         block_dev
+	# see scst/README: Change the ALUA state to "transitioning". At this moment all open
+	# file handles will be closed.
+        scst_sysfs_write "transitioning" ${dev_group}/target_groups/${tpg}/state || {
+            ocf_log err "ALUA - Unable to set state to transitioning - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
+            exit $OCF_ERR_GENERIC
+        }
+	# Be sure all in-flight data is flushed ...
         flushbufs
+	# ... before switching to desired state
         scst_sysfs_write "${2}" ${dev_group}/target_groups/${tpg}/state || {
             ocf_log err "ALUA - Unable to set state to ${2} - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
