SCSTLogicalUnit: set scsi_sn, scsi_id and venor_id during start

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -387,14 +387,34 @@ SCSTLogicalUnit_start() {
             exit $OCF_ERR_GENERIC
         }
     fi
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Add device ${OCF_RESOURCE_INSTANCE} whith path ${OCF_RESKEY_path}."
 
-    # Set the SCSI serial number aka T10 device id
-    if [ -n "${OCF_RESKEY_t10_device_id}" ]; then
-        echo "${OCF_RESKEY_t10_device_id}" >${dev_path}/t10_dev_id || {
-            ocf_log err "Unable to set T10 device id ${OCF_RESKEY_t10_device_id} for device ${OCF_RESOURCE_INSTANCE}.";
+    # Set the SCSI device id aka T10 device id
+    if [ -n "${OCF_RESKEY_scsi_id}" ]; then
+        echo "${OCF_RESKEY_scsi_id}" >${dev_path}/t10_dev_id || {
+            ocf_log err "Unable to set T10 device id ${OCF_RESKEY_scsi_id} for device ${OCF_RESOURCE_INSTANCE}.";
             exit $OCF_ERR_GENERIC
         }
     fi
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set SCSI device id to ${OCF_RESKEY_scsi_id}."
+
+    # Set the SCSI device serial number aka unit serial number
+    if [ -n "${OCF_RESKEY_scsi_sn}" ]; then
+        echo "${OCF_RESKEY_scsi_sn}" >${dev_path}/usn || {
+            ocf_log err "Unable to set usn ${OCF_RESKEY_scsi_sn} for device ${OCF_RESOURCE_INSTANCE}.";
+            exit $OCF_ERR_GENERIC
+        }
+    fi
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set SCSI serial number to ${OCF_RESKEY_scsi_sn}."
+
+    # Set the SCSI vendor id
+    if [ -n "${OCF_RESKEY_vendor_id}" ]; then
+        echo "${OCF_RESKEY_vendor_id}" >${dev_path}/t10_vend_id || {
+            ocf_log err "Unable to set usn ${OCF_RESKEY_vendor_id} for device ${OCF_RESOURCE_INSTANCE}.";
+            exit $OCF_ERR_GENERIC
+        }
+    fi
+    ocf_log debug "${OCF_RESOURCE_INSTANCE}: Set vendor id to ${OCF_RESKEY_vendor_id}."
 
     # Set all additional parameters
     for param in ${OCF_RESKEY_additional_parameters}; do
