SCSTLogicalUnit: rewrite update_alua_access_state() from LIO to SCST

diff --git a/heartbeat/SCSTLogicalUnit b/heartbeat/SCSTLogicalUnit
--- a/heartbeat/SCSTLogicalUnit
+++ b/heartbeat/SCSTLogicalUnit
@@ -286,21 +286,30 @@ scst_sysfs_write() {
 
 update_alua_access_state() {
     local tpg="$1"
+    local dev_group="${SCST_BASE}/device_groups/${OCF_RESOURCE_INSTANCE}"
 
     case $2 in
         standby)
-            ocf_run tcm_node --setaluastate iblock_${OCF_RESKEY_lio_iblock}/${OCF_RESOURCE_INSTANCE} ${tpg} s || {
-                ocf_log error "Unable to set ALUA access state for lun_${OCF_RESKEY_lun}/${OCF_RESOURCE_INSTANCE}!";
+            scst_sysfs_write "0" ${dev_group}/target_groups/${tpg}/preferred || {
+                ocf_log err "Unable to set preferred to 0 - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
                 exit $OCF_ERR_GENERIC
             }
-            ocf_log debug "ALUA: $tpgn is not optimized"
+            scst_sysfs_write "standby" ${dev_group}/target_groups/${tpg}/state || {
+                ocf_log err "Unable to set state to standby - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
+                exit $OCF_ERR_GENERIC
+            }
+            ocf_log debug "${OCF_RESOURCE_INSTANCE} - ALUA: TPG ${tpg} is standby/not preferred."
             ;;
         optimized)
-            ocf_run tcm_node --setaluastate iblock_${OCF_RESKEY_lio_iblock}/${OCF_RESOURCE_INSTANCE} ${tpg} o || {
-                ocf_log error "Unable to set ALUA access state for lun_${OCF_RESKEY_lun}/${OCF_RESOURCE_INSTANCE}!";
+            scst_sysfs_write "1" ${dev_group}/target_groups/${tpg}/preferred || {
+                ocf_log err "Unable to set preferred to 0 - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
                 exit $OCF_ERR_GENERIC
             }
-            ocf_log debug "ALUA: ${optimized} is now optimized"
+            scst_sysfs_write "active" ${dev_group}/target_groups/${tpg}/state || {
+                ocf_log err "Unable to set state to active - TPG ${tpg}, device_group ${OCF_RESOURCE_INSTANCE}.";
+                exit $OCF_ERR_GENERIC
+            }
+            ocf_log debug "${OCF_RESOURCE_INSTANCE} - ALUA: TPG ${tpg} is optimized/preferred."
             ;;
     esac
 
